### ISSUE TITLE
Visualize Code for San Jose zoning data using CartoDB

### ISSUE THREAD

**Issue by evankroske** [codeforsanjose/Project-Ideas#33]
Here's the data:

http://www.sanjoseca.gov/DocumentCenter/View/14148

And here's CartoDB:

https://cartodb.com/

**Comment by evankroske** [comment]
Also, add a page to the HackNightProjects website to embed the map or link to it:

https://github.com/codeforsanjose/HackNightProjects/tree/gh-pages

**Comment by jamestyack** [comment]
@evankroske here's a really nice video Jared found online with great tutorial of CartoDB for people new to it https://vimeo.com/59791629  Maybe we can add a toolset/resources section on the main wiki with links/howtos for simple to use tools like mapbox and cartodb? (another 2 hour project idea I can add!)

**Comment by sagarwal10** [comment]
I played with Cartodb (for the first time) and created a map using the pd_density column (I assume this means population density). Is there any other column we should be creating maps on?

https://slowreader.cartodb.com/viz/9ca49d88-6448-11e5-91cb-0ec6f7c8b2b9/public_map

**Comment by evankroske** [comment]
I'm not sure what your map means. I was hoping that someone would make a map that shows me what can be done with all the land in San Jose, like this:

http://www.mountainview.gov/civicax/filebank/blobdload.aspx?BlobID=10990

I'm not sure whether the zip file mentioned above contains the data you need. I think that I found a page that contains the data I'm interested in:

http://us-city.census.okfn.org/entry/sanjose/zoning

It's probably in the "Basemap" and "General Plan" files.

**Comment by sagarwal10** [comment]
Got it. I wasn't sure what needed to be visualized.

I have now created a map of the different Zones (stuff like R-1-5, R-1-8, WATER) using the data in the zip file that was referenced in the first entry of this post). This should be what you were looking for:

https://slowreader.cartodb.com/viz/32204b0c-65aa-11e5-8ade-0e23c2a19d43/public_map

However it looks like San Jose already has this online:
http://www.sanjoseca.gov/index.aspx?NID=2037

 My map looks slightly different because of different colors and CartoDB only seems to allow 9 different zone categories to be shown and everything else is shown as OTHER. But the data looks the same - I verified this by clicking on different regions of the map.

**Comment by evankroske** [comment]
Cool! Your map is better than San Jose's because we can modify it to show only some zoning categories or query it for what percentage of land is available for hotels, for example. Could you add a link to your map from the following page?

https://github.com/codeforsanjose/HackNightProjects/blob/gh-pages/index.html

Click the pencil to start editing.

**Comment by jamestyack** [comment]
Very cool, great work. By the way, I added tools tutorial to wiki under this repo so feel free to add to it.

**Comment by mthong** [comment]
Looks lovely. Can we add some documentation explaining what the map is, what the zones are (or where to find zoning definitions, even if just a link back to City website), and what this map does that the City map doesn't do. (I think it's ok even if it doesn't add any particularly new features -- it may be useful enough to have a web-based map that anyone can manipulate for other purposes as needed.) 

How would I query the map to find out the amount of area in a given zone? I would love to be able to do that for my economic development work. 

For public sharing, I think it'd be ideal to display all the zones, if possible, because you don't know which zones are going to be relevant to viewers...or to do more intentional simplification of the zones (E.g. lump all low-density residential together as one zone). 

Also, although the zoning doesn't change that frequently, we'd want to make sure that the CartoDB version of the map stays up to date with the latest zoning layer.

**Comment by sagarwal10** [comment]
Sure I can add a link to index.html. Should I add it to the body as a new <p>aragraph after the Instructions for new members? 

Couple of things about the map:

1. It was hard to find the zoning descriptions. Finally found it in section 20 of 

    https://www.municode.com/library/ca/san_jose/codes/code_of_ordinances?nodeId=TIT20ZO_CH20.10GEPRZODI_20.10.080CIDIINZO

I can either state that as instructions or extract out the table of zoning codes. 

2. The map is pretty much static. it cannot be queried AFAIK. You have to create an account
inside cartodb to make any changes. As far as finding out the square area occupied by 
certain zones, it doesn't look like its part of the data set. I tried to find out more about the
Google Earth KMZ file format but couldn't find out anything else.

3. With a free account in cartodb, one cannot map more than 10 zones. 

4. Keeping it upto date with the latest zoning layer would also require a person putting in effort into it - its not automated.

**Comment by evankroske** [comment]
Yes, please add it as a paragraph.

Regarding querying the map, anybody should be able to sign up for CartoDB
and query the data using PostGIS.

**Comment by jamestyack** [comment]
Seems like great work so far. Purpose of using CartoDB is to get simple ideas/POCs up and running very quickly that can spark off other ideas/projects and seems like that's happening here.

**Comment by mthong** [comment]
Aha. Thanks for the clarification @jamestyack. I think I was getting confused between this being a public-facing tool rather than a mini-project primarily for experimenting and developing proofs-of-concept.

In other news, I just learned that we can get a 1GB CartoDB account for our Brigade: 
http://forum.codeforamerica.org/t/free-cartodb-for-your-brigades/243/2

I don't think we've signed up for our account yet. I'll share the details when I have them.

**Comment by sagarwal10** [comment]
I've proposed a change to add the links to the map and the San Jose zoning definition document: 

https://github.com/codeforsanjose/HackNightProjects/compare/gh-pages...sagarwal10:patch-1

**Comment by evankroske** [comment]
Thanks! Could you create a pull request for this change? You can do this by
clicking "Create pull request" on the change you sent me.

**Comment by sagarwal10** [comment]
Created a pull request: 

https://github.com/codeforsanjose/HackNightProjects/pull/8


Date: Tue, 6 Oct 2015 08:33:24 -0700

**Comment by mthong** [comment]
Just for inspiration: here's a cool full-blown zoning app developed by Chicaco's Brigade:
http://secondcityzoning.org/
